apiVersion: v1
kind: Namespace
metadata:
  name: aks-dev-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: __ACRFullImageName__
        ports:
        - containerPort: 5209
        env:
        - name: CorsAllowedHosts
          value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-backend
spec:
  type: LoadBalancer
  ports:
  - port: 5209
  selector:
    app: todo-api