name: deploy-aks-package
on:
    push:
      branches: 
        [ main ]
      paths:
        - '**'
        - '.github/workflows/deploy-aks-package.yml'

    workflow_dispatch: {}
env:
    VERSION: v1
    ACR_RESOURCE_GROUP: red-aks-demo-rg
    AZURE_CONTAINER_REGISTRY: myAksRepo
    CLUSTER_NAME: myAKSCluster
    CLUSTER_RESOURCE_GROUP: red-aks-demo-rg
    CONTAINER_NAME: todo-api
    DEPLOYMENT_MANIFEST_PATH: |
        ./azure-aks-deployment.yaml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            #- name: Build and push image to ACR
              #run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./Dockerfile ./
            
            - name: Build and push container image to registry
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}.${{ github.run_number }}
                file: ./Dockerfile
                context: ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}.${{ github.run_number }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: aks-dev-ns
