name: Trigger container apps deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'

  # Allow mannually trigger 
  workflow_dispatch:      

env:
  version: 'v1.0'
  location: 'eastus2'
  resource-group-name: 'red-eus2-aca-rg'
  log-analytics-workspace-name: 'red-logworkspace-aca-01'
  aca-env-name: 'dev-env'
  registry-name: 'redeus2containerreg01'
  registry-sku: 'Standard'
  image-name: 'todo-webapi'
  container-name: 'todo-webapi-aca'
  client-container-name: 'todo-blazorclient-aca'
  client-container-rg-name: 'red-eus2-aca-rg'

jobs:
  expose-env:
    runs-on: ubuntu-latest

    outputs:
      rg-name: ${{ steps.print-var.outputs.rg-name }}
      location-name: ${{ steps.print-var.outputs.location-name }}
      law-name: ${{ steps.print-var.outputs.law-name }}
      aca-env-name: ${{ steps.print-var.outputs.aca-env-name }}
      reg-name: ${{ steps.print-var.outputs.reg-name }}
      reg-sku: ${{ steps.print-var.outputs.reg-sku }}
      
    steps:
      - name: Print inputs passed to the reusable workflow
        id: print-var
        run: |
          echo "rg-name=${{ env.resource-group-name }}" >> $GITHUB_OUTPUT
          echo "location-name=${{ env.location }}" >> $GITHUB_OUTPUT
          echo "law-name=${{ env.log-analytics-workspace-name }}" >> $GITHUB_OUTPUT
          echo "aca-env-name=${{ env.aca-env-name }}" >> $GITHUB_OUTPUT
          echo "reg-name=${{ env.registry-name }}" >> $GITHUB_OUTPUT
          echo "reg-sku=${{ env.registry-sku }}" >> $GITHUB_OUTPUT

  build-infra:
    needs: expose-env

    uses: anotherRedbeard/reusable-workflows/.github/workflows/create-aca-infra.yml@main
    with:
      rg-name: ${{ needs.expose-env.outputs.rg-name }}
      location: ${{ needs.expose-env.outputs.location-name }}
      law-name: ${{ needs.expose-env.outputs.law-name }}
      aca-env-name: ${{ needs.expose-env.outputs.aca-env-name }}
      reg-name: ${{ needs.expose-env.outputs.reg-name }}
      reg-sku: ${{ needs.expose-env.outputs.reg-sku }}
    secrets:
      azure-creds: ${{ secrets.AZURE_CREDENTIALS }}

  build:
    runs-on: ubuntu-latest
    needs: build-infra

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Container Registry Credentials
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ACR_USERNAME=$(az acr credential show -n ${{ env.registry-name }} --query username --out tsv)
            ACR_PASSWORD=$(az acr credential show -n ${{ env.registry-name }} --query passwords[0].value --out tsv)
            echo "::add-mask::$ACR_PASSWORD"
            echo ACR_USERNAME=$ACR_USERNAME >> $GITHUB_ENV
            echo ACR_PASSWORD=$ACR_PASSWORD >> $GITHUB_ENV

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry-name }}.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.registry-name }}.azurecr.io/${{ env.image-name }}:${{ env.version }}.${{ github.run_number }}
          file: ./Dockerfile
          context: ./

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Container Registry Credentials
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ACR_USERNAME=$(az acr credential show -n ${{ env.registry-name }} --query username --out tsv)
            ACR_PASSWORD=$(az acr credential show -n ${{ env.registry-name }} --query passwords[0].value --out tsv)
            echo "::add-mask::$ACR_PASSWORD"
            echo ACR_USERNAME=$ACR_USERNAME >> $GITHUB_ENV
            echo ACR_PASSWORD=$ACR_PASSWORD >> $GITHUB_ENV

      - name: Get Client Container url
        id: get-container-url
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            CLIENT_CONTAINER_URL=$(az containerapp show -n ${{ env.client-container-name }} -g ${{ env.client-container-rg-name }} --query properties.configuration.ingress.fqdn --out tsv || echo "Error")
            echo CLIENT_CONTAINER_URL=$CLIENT_CONTAINER_URL >> $GITHUB_ENV

      - name: Handle Continaer url failure
        if: ${{ steps.get-container-url.outputs.CLIENT_CONTAINER_URL == 'Error' }}
        run: |
          echo "CLIENT_CONTAINER_URL not obtained. Setting default value."
          echo "CLIENT_CONTAINER_URL=default-value" >> $GITHUB_ENV

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp create -n ${{ env.container-name }} -g ${{ env.resource-group-name }} \
              --image ${{ env.registry-name }}.azurecr.io/${{ env.image-name }}:${{ env.version }}.${{ github.run_number }} \
              --environment ${{ env.aca-env-name }} --registry-server ${{ env.registry-name }}.azurecr.io \
              --registry-username ${{ env.ACR_USERNAME }} \
              --registry-password ${{ env.ACR_PASSWORD }} \
              --ingress external --target-port 5209 \
              --env-vars CorsAllowedHosts=$(if [ ${{ env.CLIENT_CONTAINER_URL }} == '' ]; then echo "*"; else echo "https://${{ env.CLIENT_CONTAINER_URL }}"; fi) \
              AppConfig__Endpoint=${{ secrets.APP_CONFIG_URL }} \
              ASPNETCORE_ENVIRONMENT=Staging

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
